readers:
  - "urn:github:526301"
assets:
  settings.xml: yegor256/home#assets/requs/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
  secring.gpg: yegor256/home#assets/secring.gpg
install: |-
  export GEM_HOME=~/.ruby
  export GEM_PATH=$GEM_HOME:$GEM_PATH
  bundle install
  pdd -f /dev/null
  easy_install src/requs_pygment
merge:
  script: |-
    mvn clean install -Pqulice --errors --settings ../settings.xml
    mvn clean site -Psite --settings ../settings.xml
deploy:
  script: |-
    echo 'nothing to deploy'
    exit -1
release:
  sensitive:
    - setting.xml
  script: |-
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pqulice -Psonatype -Prequs --errors --settings ../settings.xml
    mvn clean site-deploy -Pgh-pages -Psite --errors --settings ../settings.xml
