# SPDX-FileCopyrightText: Copyright (c) 2009-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/rultor-image:1.24.0
readers:
  - "urn:github:526301"
assets:
  settings.xml: yegor256/home#assets/requs/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
  secring.gpg: yegor256/home#assets/secring.gpg
install: |-
  pdd -f /dev/null
merge:
  script: |-
    mvn clean install -Pqulice --errors --settings ../settings.xml
    mvn clean site -Psite --settings ../settings.xml
release:
  sensitive:
    - setting.xml
  script: |-
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pqulice -Psonatype -Prequs --errors --settings ../settings.xml
