<?="<?xml version=\"1.0\" encoding=\"utf-8\" ?>\n"?>
<? header('Content-type: application/xhtml+xml') ?>
<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" type="text/css" href="global.css" />
    <title>RQDQL, Requirements Definition and Query Language</title>
</head>
<body>

    <? if (file_exists($file)): ?>
        <? include $file ?>
    <? else: ?>
        <p>File not found</p>
    <? endif; ?>
    
</body>
</html>