name: requs.org
markdown: kramdown
highlighter: pygments
permalink: :title.html

# see https://github.com/noct/jekyll-sass
gems: ['jekyll-sass']
sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: false

# see https://github.com/kinnetica/jekyll-plugins
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/rss.xml"
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequence"
  priority_name: "priority"
