# SPDX-FileCopyrightText: Copyright (c) 2009-2025, Yegor Bugayenko
# SPDX-License-Identifier: MIT

#
# Just run "bundle"
#
source 'https://rubygems.org'

gem 'jekyll', '4.0.1'
gem 'jekyll-sass', '1.1.0'
gem 'jekyll-sass-converter', '2.1.0'
