/*
 * SPDX-FileCopyrightText: Copyright (c) 2009-2025 Yegor Bugayenko
 * SPDX-License-Identifier: MIT
 */
package org.requs.maven;

import com.jcabi.log.Logger;
import java.io.File;
import java.io.IOException;
import java.util.Locale;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import org.apache.maven.doxia.sink.Sink;
import org.apache.maven.doxia.sink.SinkFactory;
import org.apache.maven.doxia.siterenderer.Renderer;
import org.apache.maven.plugins.annotations.Component;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.project.MavenProject;
import org.apache.maven.reporting.AbstractMavenReport;
import org.apache.maven.reporting.MavenReportException;
import org.requs.Compiler;
import org.slf4j.impl.StaticLoggerBinder;

/**
 * Generate site reports.
 *
 * @since 1.1
 * @checkstyle ClassDataAbstractionCoupling (500 lines)
 * @checkstyle VisibilityModifierCheck (500 lines)
 */
@Mojo(name = "default")
@SuppressWarnings("PMD.ExcessiveImports")
public final class ReportMojo extends AbstractMavenReport {

    /**
     * The Maven Project.
     */
    @Parameter(defaultValue = "${project}", readonly = true)
    public transient MavenProject project;

    /**
     * Output directory.
     */
    @Parameter(property = "project.reporting.outputDirectory", required = true)
    public transient File output;

    /**
     * The source directory.
     */
    @Parameter(
        required = true,
        defaultValue = "${basedir}/src/main/requs"
    )
    public transient File source;

    /**
     * Optional properties/options.
     * @since 1.14
     */
    @Parameter()
    @SuppressWarnings("PMD.UseConcurrentHashMap")
    public transient Map<String, String> options =
        new ConcurrentHashMap<>(0);

    /**
     * Doxia Site Renderer component.
     */
    @Component
    public transient Renderer renderer;

    @Override
    public String getOutputName() {
        return "requs";
    }

    @Override
    public String getName(final Locale locale) {
        return "Requs";
    }

    @Override
    public String getDescription(final Locale locale) {
        return "Requs Specification";
    }

    @Override
    public Renderer getSiteRenderer() {
        return this.renderer;
    }

    @Override
    public String getOutputDirectory() {
        return this.output.getAbsolutePath();
    }

    @Override
    public MavenProject getProject() {
        return this.project;
    }

    @Override
    public void executeReport(final Locale locale) throws MavenReportException {
        throw new MavenReportException("not supported");
    }

    @Override
    public void generate(final Sink sink, final SinkFactory factory,
        final Locale locale) {
        if (!this.source.exists()) {
            Logger.info(this, "source directory %s is absent", this.source);
            return;
        }
        StaticLoggerBinder.getSingleton().setMavenLog(this.getLog());
        final File home = new File(
            this.getOutputDirectory(),
            this.getOutputName()
        );
        if (home.mkdirs()) {
            Logger.info(this, "site directory %s created", home);
        }
        try {
            new Compiler(this.source, home, this.options).compile();
        } catch (final IOException ex) {
            throw new IllegalStateException(ex);
        }
        this.front(sink);
    }

    /**
     * Make a front page.
     * @param sink Sink to use
     */
    private void front(final Sink sink) {
        sink.section1();
        sink.sectionTitle1();
        sink.text("Requs SRS");
        sink.sectionTitle1_();
        sink.paragraph();
        sink.text("This page contains ");
        sink.link(String.format("%s/requs.xml", this.getOutputName()));
        sink.text("Software Requirements Specification (SRS)");
        sink.link_();
        sink.text(" generated by requs compiler.");
        sink.paragraph();
        sink.text("More information you can get at ");
        sink.link("http://www.requs.org");
        sink.text("www.requs.org");
        sink.link_();
        sink.text(".");
        sink.paragraph_();
        sink.section1_();
    }

}
