<?="<?xml version=\"1.0\" encoding=\"utf-8\" ?>\n"?>
<!--
 * RQDQL.com, Requirements Definition and Query Language
 *
 * Redistribution and use in source and binary forms, with or 
 * without modification, are PROHIBITED without prior written 
 * permission from the author. This product may NOT be used 
 * anywhere and on any computer except the server platform of 
 * rqdql.com. located at www.rqdql.com. If you received this 
 * code occasionally and without intent to use it, please report 
 * this incident to the author by email: team@rqdql.com
 *
 * @author Yegor Bugayenko <egor@tpc2.com>
 * @copyright Copyright (c) rqdql.com, 2010
 * @version $Id: index.php 2236 2010-07-03 17:26:54Z yegor256@yahoo.com $
 *
 -->
<? header('Content-type: application/xhtml+xml') ?>
<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" type="text/css" href="views/css/global.css" />
    <link rel="stylesheet" type="text/css" href="views/css/example.css" />
    <title>RQDQL, Requirements Definition and Query Language</title>
</head>
<body>

    <? if (file_exists($file)): ?>
        <? include $file ?>
    <? else: ?>
        <p>File not found</p>
    <? endif; ?>
    
</body>
</html>