<!--
 * RQDQL.com, Requirements Definition and Query Language
 *
 * Redistribution and use in source and binary forms, with or 
 * without modification, are PROHIBITED without prior written 
 * permission from the author. This product may NOT be used 
 * anywhere and on any computer except the server platform of 
 * rqdql.com. located at www.rqdql.com. If you received this 
 * code occasionally and without intent to use it, please report 
 * this incident to the author by email: team@rqdql.com
 *
 * @author Yegor Bugayenko <egor@tpc2.com>
 * @copyright Copyright (c) rqdql.com, 2010
 * @version $Id: index.php 2236 2010-07-03 17:26:54Z yegor256@yahoo.com $
 *
 -->

<h1>RQDQL Instant Example</h1>

<div id="front">
    <textarea id="example"></textarea>
    <div id="status">
    </div>
</div>

<script type="text/javascript" src="http://code.jquery.com/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="views/js/rqdql.js"></script>
<script type="text/javascript" src="views/js/example.js"></script>

<table id="lines">
<colgroup>
    <col id="line"></col>
    <col id="text"></col>
    <col id="comment"></col>
</colgroup>
<thead>
    <tr>
        <th>Line</th>
        <th>Content</th>
        <th>Found elements</th>
    </tr>
</thead>
<tbody>
</tbody>
</table>

<pre id="xml"></pre>